### PR TITLE
Increasing the performance of the function

### PR DESCRIPTION
**Pull request by aricci10**
Hello, 

Firstly, thank you for the very well done and commented function. The function actually works very good and helped me a lot during a project. However, the function in a very inefficient way. There are many python loops which are unnecessary and make the function very slow, especially for big data samples. I decided to improve the efficiency of the function by using numpy, and the results are fantastic as you may be able to see in the plot and notebook I'm uploading. 
[times.pdf](https://github.com/jewettaij/superpose3d/files/4315369/times.pdf).

### CODE REVIEW

**Comment by jewettaij** [comment]
Thank you for this contribution!
Thank you for leaving the original for-loops in the code as comments.
(It helps me at least, since I am not a numpy expert.  I am learning more about how to use numpy correctly by reading your code.)

## Issues
On my computer, this code fails my unit test ("test_superpose3d.py") for two trivial reasons:

1) I need to add "scipy>=1.3.0" to my "requirements.txt" file.  (I am happy to do this.)
2) The "as_matrix()" member function is not avialable on my version of scipy (v1.3.1).  I think it's a mistake to make a change that requires the latest version of scipy.  So I am commenting out a small portion of your code:

```python
    """
    the_rotation = R.from_quat(p)
    aaRotate = the_rotation.as_matrix()
    """
```
...and replacing it with my original code:
```
    aaRotate = np.empty((3,3))
    aaRotate[0][0] =  (p[0]*p[0])-(p[1]*p[1])-(p[2]*p[2])+(p[3]*p[3])
    aaRotate[1][1] = -(p[0]*p[0])+(p[1]*p[1])-(p[2]*p[2])+(p[3]*p[3])
    aaRotate[2][2] = -(p[0]*p[0])-(p[1]*p[1])+(p[2]*p[2])+(p[3]*p[3])
    aaRotate[0][1] = 2*(p[0]*p[1] - p[2]*p[3]);
    aaRotate[1][0] = 2*(p[0]*p[1] + p[2]*p[3]);
    aaRotate[1][2] = 2*(p[1]*p[2] - p[0]*p[3]);
    aaRotate[2][1] = 2*(p[1]*p[2] + p[0]*p[3]);
    aaRotate[0][2] = 2*(p[0]*p[2] + p[1]*p[3]);
    aaRotate[2][0] = 2*(p[0]*p[2] - p[1]*p[3]);
```
Hopefully this should not slow down the code that much because it only happens once.  (It is not in a for-loop.)

I also am worried about using **R.from_quat(p)**, because "p" is not a rotation quaternion.  (It is a quaternion with the elements in the wrong order:  In modern usage, the first element of a quaternion is cos(theta), and the last the elements are the rotation axis.  However, in the 1988 paper, H.R.Diamond decided to use a different quaternion format which is incompatible with the modern format.  In his paper, the first 3 elements of *p* are the rotation axis.)  The quaternion for the rotation is calculated at the end of the __init__.py file:
```python
        q[0] = p[3]
        q[1] = p[0]
        q[2] = p[1]
        q[3] = p[2]
```
It would not be hard to fix this.  However if I fix the order, then the "p" variable in the code would not match the "p" variable in the paper.  (Perhaps I should not worry about this small issue.)

I will accept this pull request, and then follow up with a commit with my changes.  (Since I can't figure out how to edit the pull request.)

Thanks again!
-Andrew
(I'm curious what you used this code for.)

**Comment by jewettaij** [comment]
My apologies.  I intended to approve that pull request.  Attempting to do this retroactively...

**Comment by aricci10** [comment]
Thank you for accepting the pull request. From the way your code was written, I have the feeling that you come from a C/C++ background. The thing is that since Python is interpreted (as opposed to C), pure Python is waaaay slower than C if you try to run the loops by brute force. However, this is not a problem with proper use of NumPy which is basically a C interface for Python, so it's just a bit (a really tiny bit) slower than pure C. 

Take a look into the scipy rotation library which has a very easy way to use quaternions for rotations. The "from_quat()" actually expects the order to be [x,y,z,w] which is the one obtained from the method so it should work straight away. I the real part being at the beginning or end of the quaternion is just a notation matter and as long as one is consistent with the usage both orders are okay. Just be careful how each library is expecting them to be ordered.  

I was using the library to find the optimal rotation of the data points obtained from two Xbox Kinects. It worked perfectly. I will post some results soon

**Comment by jewettaij** [comment]
> Thank you for accepting the pull request.
Thanks for submitting it!

> Take a look into the scipy rotation library which has a very easy way to use quaternions for rotations. The "from_quat()" actually expects the order to be [x,y,z,w] which is the one obtained from the method so it should work straight away. I the real part being at the beginning or end of the quaternion is just a notation matter and as long as one is consistent with the usage both orders are okay. Just be careful how each library is expecting them to be ordered.

This is useful to know.  I assumed it was [w,x,y,z] ([link1](https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation), [link2](https://mathworld.wolfram.com/Quaternion.html)).
(I am a little bit surprised that after so much time no dominant convention has emerged.)
```python
    from scipy.spatial.transform import Rotation as R
    # :
    the_rotation = R.from_quat(p)
    aaRotate = the_rotation.as_matrix()
```
This may sound silly, but I prefer to avoid adding a dependency on scipy if it's not necessary.  But I will leave your modification to this portion of the code in a comment so that people can see your alternative implementation.  (And I think seeing your code might people understand what this portion of the code does.)  I have preserved all of your other changes.

> I was using the library to find the optimal rotation of the data points obtained from two Xbox Kinects. It worked perfectly. I will post some results soon

Ahh.  That explains why you have so many points....
(So far, I have mostly been using it to compare the conformations of small molecules.)

I'm surprised you decided to use the code in this repository instead of a larger repository with more features (such as ICP, for example).  But I'm very glad this code was useful to somebody.

Take care.

**Pull request merged**
